apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      initContainers:
      - name: init-db
        image: abdouhenna/flask-app:latest
        command: ["python", "/app/init_db.py"]
        env:
        - name: DB_HOST
          value: "db"  # لازم يكون نفس اسم service تبع قاعدة البيانات
        - name: DB_NAME
          value: "yourdbname"
        - name: DB_USER
          value: "yourdbuser"
        - name: DB_PASSWORD
          value: "yourdbpassword"
      containers:
      - name: flask-container
        image: abdouhenna/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_NAME
          value: "yourdbname"
        - name: DB_USER
          value: "yourdbuser"
        - name: DB_PASSWORD
          value: "yourdbpassword"
